import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/Components/Header'
import  MyContex from '@/Components/helper/Contex'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyContex>
        <Header/>
        {children}
          </MyContex></body>
    </html>
  )
}
